### ISSUE TITLE
Remote Access of Stick

### ISSUE THREAD

**Issue by ebnerjoh** [W00D00/home-assistant-elero#39]
Hi, its not an issue, its a question:

My Home Assistant installation is running in the basement, but my elero shutters are in the third floor. 

I have an RPi running in the third floor.

Would there be an option to either remotley connect from home assistant to a stick which is on a different system or setup a eleror2mqtt bridge?

Best Regards,
Johannes

**Comment by caco3** [comment]
Since you anyway have an RPi running on the 3th floor, could you install a 2nd Homeassistant instance there?
And just connect the Elero Stick there?
I think this would be the easiest approach, not needing Software Development.

You then could create some MQTT sensors which consume a MQTT message (sent from the first HA instance or any other MQTT client) and trigger the Elero actions.

I have it working that way on my system. (MQTT->Elero)

**Comment by ebnerjoh** [comment]
That is a good feeback. a stupid other question:

It seems the USB Transmitter is not produced anymore and it is not that cheap.
Any experience with the Elero Center, which is not really more expensive anymore?

**Comment by andy-st** [comment]
> That is a good feeback. a stupid other question:
> 
> It seems the USB Transmitter is not produced anymore and it is not that cheap. Any experience with the Elero Center, which is not really more expensive anymore?

I think the newest solution is Yubii Home?
https://www.yubiihome.com

**Comment by matrixx567** [comment]
It seems there is another gateway that supports Elero.  

https://community.home-assistant.io/t/mediola2mqtt-simple-mediola-to-mqtt-bridge-with-ha-support/288188
